//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HastaneEntities : DbContext
    {
        public HastaneEntities()
            : base("name=HastaneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calisanlar> Calisanlar { get; set; }
        public virtual DbSet<Doktorlar> Doktorlar { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<Randevular> Randevular { get; set; }
        public virtual DbSet<DoktorTc> DoktorTc { get; set; }
        public virtual DbSet<HastaTc> HastaTc { get; set; }
        public virtual DbSet<Reçeteler> Reçeteler { get; set; }
        public virtual DbSet<CalisanTc> CalisanTc { get; set; }
        public virtual DbSet<Raporlar> Raporlar { get; set; }
    }
}
