//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raporlar
    {
        public int Id { get; set; }
        public string HastaAdi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<System.DateTime> RaporBaslangic { get; set; }
        public Nullable<System.DateTime> RaporBitis { get; set; }
        public string RaporSebebi { get; set; }
        public string RaporuVerenDoktor { get; set; }
    }
}
